'use strict';

var
  moment = require('moment'),
  usps = require('../../');

usps.configure(require('../options'));

module.exports = {
  sdcGetLocations: function (test) {
    usps.sdcServiceStandards.sdcGetLocations(
      { mailClass: '0',
        originZIP: '70601',
        destinationZIP: '98101',
        acceptDate: moment().format('D-MMM-YYYY'),
        acceptTime: '0900',
        nonEMDetail: true },
      function (error, response) {
        test.expect(2);

        test.ifError(error);
        test.deepEqual(
          response,
          { release: '8',
            callerID: '4',
            sourceID: '004',
            mailClass: '0',
            originZIP: '70601',
            originCity: 'LAKE CHARLES',
            originState: 'LA',
            destZIP: '98101',
            destCity: 'SEATTLE',
            destState: 'WA',
            acceptDate: moment().format('YYYY-MM-DD'),
            acceptTime: '0900',
            nonExpeditedDetail: '1',
            expedited:
             { eAD: moment().format('YYYY-MM-DD'),
               commitment: [ { mailClass: '1',
                               commitmentName: '1-Day',
                               commitmentTime: '1030',
                               commitmentSeq: 'B0110',
                               location: { sDD: moment().add(moment().day() === 6 ? 2 : 1, 'day').format('YYYY-MM-DD'),
                                           cOT: '1645',
                                           facType: 'POST OFFICE',
                                           street: '921 MOSS ST',
                                           city: 'LAKE CHARLES',
                                           state: 'LA',
                                           zIP: '70601',
                                           isGuaranteed: '1' } },
                              { mailClass: '1',
                               commitmentName: '1-Day',
                               commitmentTime: '1030',
                               commitmentSeq: 'A0110',
                               location: { sDD: moment().add(moment().day() === 6 ? 2 : 1, 'day').format('YYYY-MM-DD'),
                                           cOT: '1645',
                                           facType: 'POST OFFICE',
                                           street: '921 MOSS ST',
                                           city: 'LAKE CHARLES',
                                           state: 'LA',
                                           zIP: '70601',
                                           isGuaranteed: '1' } },
                              { mailClass: '1',
                               commitmentName: '1-Day',
                               commitmentTime: '1500',
                               commitmentSeq: 'A0115',
                               location: { sDD: moment().add(moment().day() === 6 ? 2 : 1, 'day').format('YYYY-MM-DD'),
                                           cOT: '1645',
                                           facType: 'POST OFFICE',
                                           street: '921 MOSS ST',
                                           city: 'LAKE CHARLES',
                                           state: 'LA',
                                           zIP: '70601',
                                           isGuaranteed: '1' } },
                              { mailClass: '2',
                               commitmentName: '2-Day',
                               commitmentTime: '',
                               commitmentSeq: 'C0200',
                               location: { sDD: moment().add(moment().day() === 5 ? 3 : 2, 'day').format('YYYY-MM-DD'),
                                           cOT: '1700',
                                           facType: 'POST OFFICE',
                                           street: '921 MOSS ST',
                                           city: 'LAKE CHARLES',
                                           state: 'LA',
                                           zIP: '70601',
                                           isGuaranteed: '2' } },
                              { mailClass: '2',
                               commitmentName: '2-Day',
                               commitmentTime: '',
                               commitmentSeq: 'D0200',
                               location: { sDD: moment().add(moment().day() === 5 ? 3 : 2, 'day').format('YYYY-MM-DD'),
                                           cOT: '1700',
                                           facType: 'POST OFFICE',
                                           street: '921 MOSS ST',
                                           city: 'LAKE CHARLES',
                                           state: 'LA',
                                           zIP: '70601',
                                           isGuaranteed: '2' } },
                              { mailClass: '2',
                               commitmentName: '2-Day',
                               commitmentTime: '',
                               commitmentSeq: 'E0200',
                               location: { sDD: moment().add(moment().day() === 5 ? 3 : 2, 'day').format('YYYY-MM-DD'),
                                           cOT: '1700',
                                           facType: 'POST OFFICE',
                                           street: '921 MOSS ST',
                                           city: 'LAKE CHARLES',
                                           state: 'LA',
                                           zIP: '70601',
                                           isGuaranteed: '2' } } ] },
            nonExpedited:
             [ { mailClass: '3',
                 nonExpeditedDestType: '1',
                 eAD: moment().format('YYYY-MM-DD'),
                 cOT: '1700',
                 svcStdMsg: '3 Days',
                 svcStdDays: '3',
                 totDaysDeliver: '3',
                 schedDlvryDate: moment().add(moment().day() === 4 ? 4 : 3, 'day').format('YYYY-MM-DD'),
                 nonDlvryDays: '0' },
               { mailClass: '6',
                 nonExpeditedDestType: '1',
                 eAD: moment().format('YYYY-MM-DD'),
                 cOT: '1700',
                 svcStdMsg: '7 Days',
                 svcStdDays: '7',
                 totDaysDeliver: '7',
                 schedDlvryDate: moment().add(moment().day() === 0 ? 8 : 7, 'day').format('YYYY-MM-DD'),
                 nonDlvryDays: '0' },
               { mailClass: '3',
                 nonExpeditedDestType: '2',
                 eAD: moment().format('YYYY-MM-DD'),
                 cOT: '1700',
                 svcStdMsg: '3 Days',
                 svcStdDays: '3',
                 totDaysDeliver: '3',
                 schedDlvryDate: moment().add(moment().day() === 4 ? 4 : 3, 'day').format('YYYY-MM-DD'),
                 nonDlvryDays: '0' },
               { mailClass: '6',
                 nonExpeditedDestType: '2',
                 eAD: moment().format('YYYY-MM-DD'),
                 cOT: '1700',
                 svcStdMsg: '7 Days',
                 svcStdDays: '7',
                 totDaysDeliver: '7',
                 schedDlvryDate: moment().add(moment().day() === 0 ? 8 : 7, 'day').format('YYYY-MM-DD'),
                 nonDlvryDays: '0' },
               { mailClass: '3',
                 nonExpeditedDestType: '3',
                 hFPU: { eAD: moment().format('YYYY-MM-DD'),
                         cOT: '1700',
                         serviceStandard: { svcStdMsg: '3 Days',
                                            svcStdDays: '3',
                                            location: { totDaysDeliver: '3',
                                                        schedDlvryDate: moment().add(moment().day() === 4 ? 4 : 3, 'day').format('YYYY-MM-DD'),
                                                        nonDlvryDays: '0',
                                                        rAUName: 'MIDTOWN',
                                                        street: '301 UNION ST',
                                                        zIP: '981019998',
                                                        closeTimes: { m: '1730',
                                                                      tu: '1730',
                                                                      w: '1730',
                                                                      th: '1730',
                                                                      f: '1730',
                                                                      sa: '0000',
                                                                      su: '0000',
                                                                      h: '0000' },
                                                        city: 'SEATTLE',
                                                        state: 'WA' } } } },
               { mailClass: '6',
                 nonExpeditedDestType: '3',
                 hFPU: { eAD: moment().format('YYYY-MM-DD'),
                         cOT: '1700',
                         serviceStandard: { svcStdMsg: '7 Days',
                                            svcStdDays: '7',
                                            location: { totDaysDeliver: '7',
                                                        schedDlvryDate: moment().add(moment().day() === 7 ? 8 : 7, 'day').format('YYYY-MM-DD'),
                                                        nonDlvryDays: '0',
                                                        rAUName: 'MIDTOWN',
                                                        street: '301 UNION ST',
                                                        zIP: '981019998',
                                                        closeTimes: { m: '1730',
                                                                      tu: '1730',
                                                                      w: '1730',
                                                                      th: '1730',
                                                                      f: '1730',
                                                                      sa: '0000',
                                                                      su: '0000',
                                                                      h: '0000' },
                                                        city: 'SEATTLE',
                                                        state: 'WA' } } } } ] },
          'sdcServiceStandards.sdcGetLocations does not return expected response'
        );

        test.done();
      }
    );
  }
};